# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Charybdis Test'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["charybdis_left","charybdis_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_MOUSE_LAYER_INDEX=3\nCONFIG_MOUSE_LAYER_ACTIVE_MS=750"]'

