# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build My Corne-ish Zen v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[ "corneish_zen_v2_left","corneish_zen_v2_right" ]'
      nav: 'vi'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y\nCONFIG_IL0323_INVERT=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2 ftc/zmk/mouse-ftc"]'
