# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "corne"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["QWERTY"]'
      shield: '["corne_left","corne_right"]'
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2"]'
      nav: '["vi"]'
