# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Xiao Shields'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao"]'
      shield: '[
        "clog_v2_left","clog_v2_right",
        "hummingbird",
        "revxlp",
        "rommana_left","rommana_right",
        "totem_left","totem_right",
        "xmk",
        "zaphod_lite"
      ]'
